/* This file has been generated. Every time you change cxx-attrnames.def it will be regenerated */
#include "cxx-attrnames.h"
#include "cxx-ast.h"
#include "cxx-tltype.h"
char LANG_ACCESSED_ENTITY[] = "lang.accessed_entity";
char LANG_ACCESSED_MEMBER[] = "lang.accessed_member";
char LANG_CALLED_EXPRESSION[] = "lang.called_expression";
char LANG_CASTED_EXPRESSION[] = "lang.casted_expression";
char LANG_CAST_TYPE[] = "lang.cast_type";
char LANG_CLASS_SPECIFIER_SYMBOL[] = "lang.class_specifier_symbol";
char LANG_COMPOUND_STATEMENT_LIST[] = "lang.compound_statement_list";
char LANG_CONDITIONAL_EXPRESSION[] = "lang.conditional_expression";
char LANG_CONDITIONAL_FALSE_EXPRESSION[] = "lang.conditional_false_expression";
char LANG_CONDITIONAL_TRUE_EXPRESSION[] = "lang.conditional_true_expression";
char LANG_DECLARATION_DECLARATORS[] = "lang.declaration_declarators";
char LANG_DECLARATION_SPECIFIERS[] = "lang.declaration_specifiers";
char LANG_DECLARED_NAME[] = "lang.declared_name";
char LANG_DECLARED_PARAMETER[] = "lang.declared_parameter";
char LANG_ENUM_SPECIFIER_SYMBOL[] = "lang.enum_specifier_symbol";
char LANG_EXPRESSION_DECREMENTED[] = "lang.expression_decremented";
char LANG_EXPRESSION_INCREMENTED[] = "lang.expression_incremented";
char LANG_EXPRESSION_NESTED[] = "lang.expression_nested";
char LANG_FOR_BODY_STATEMENT[] = "lant.for_body_statement";
char LANG_FOR_CONDITION[] = "lang.for_condition";
char LANG_FOR_INIT_CONSTRUCT[] = "lang.for_init_construct";
char LANG_FOR_ITERATION_EXPRESSION[] = "lang.for_iteration_expression";
char LANG_FUNCTION_ARGUMENTS[] = "lang.function_arguments";
char LANG_FUNCTION_BODY[] = "lang.function_body";
char LANG_FUNCTION_DECLARATOR[] = "lang.function_declarator";
char LANG_FUNCTION_NAME[] = "lang.function_name";
char LANG_FUNCTION_SYMBOL[] = "lang.function_symbol";
char LANG_GCC_ATTRIBUTE_LIST[] = "lang.gcc_attribute_list";
char LANG_GCC_ATTRIBUTE_VALUE_NAME[] = "lang.gcc_attribute_value_name";
char LANG_GCC_ATTRIBUTE_VALUE_ARGS[] = "lang.gcc_attribute_value_args";
char LANG_INITIALIZER[] = "lang.initializer";
char LANG_IS_ACCESSED_MEMBER[] = "lang.is_accessed_member";
char LANG_IS_ADD_ASSIGNMENT[] = "lang.is_add_assignment";
char LANG_IS_ADDITION_OP[] = "lang.is_addition_op";
char LANG_IS_AND_ASSIGNMENT[] = "lang.is_and_assignment";
char LANG_IS_ARRAY_SUBSCRIPT[] = "lang.is_array_subscript";
char LANG_IS_ASSIGNMENT[] = "lang.is_assignment";
char LANG_IS_BINARY_OPERATION[] = "lang.is_binary_operation";
char LANG_IS_BITWISE_AND_OP[] = "lang.is_bitwise_and_op";
char LANG_IS_BITWISE_OR_OP[] = "lang.is_bitwise_or_op";
char LANG_IS_BITWISE_XOR_OP[] = "lang.is_bitwise_xor_op";
char LANG_IS_BOOLEAN_LITERAL[] = "lang.is_boolean_literal";
char LANG_IS_BREAK_STATEMENT[] = "lang.is_break_statement";
char LANG_IS_CASE_STATEMENT[] = "lang.is_case_statement";
char LANG_IS_CAST[] = "lang.is_cast";
char LANG_IS_CHARACTER_LITERAL[] = "lang.is_character_literal";
char LANG_IS_CLASS_SPECIFIER[] = "lang.is_class_specifier";
char LANG_IS_COMMA_OP[] = "lang.is_comma_op";
char LANG_IS_COMPLEMENT_OP[] = "lang.is_complement_op";
char LANG_IS_COMPOUND_STATEMENT[] = "lang.is_compound_statement";
char LANG_IS_CONDITIONAL_EXPRESSION[] = "lang.is_conditional_expression";
char LANG_IS_CONTINUE_STATEMENT[] = "lang.is_continue_statement";
char LANG_IS_DECLARATION[] = "lang.is_declaration";
char LANG_IS_DECLARATION_STATEMENT[] = "lang.is_declaration_statement";
char LANG_IS_DECLARED_NAME[] = "lang.is_declared_name";
char LANG_IS_DEFAULT_STATEMENT[] = "lang.is_default_statement";
char LANG_IS_DERREFERENCE_OP[] = "lang.is_derreference_op";
char LANG_IS_DIFFERENT_OP[] = "lang.is_different_op";
char LANG_IS_DIV_ASSIGNMENT[] = "lang.is_div_assignment";
char LANG_IS_DIVISION_OP[] = "lang.is_division_op";
char LANG_IS_DO_STATEMENT[] = "lang.is_do_statement";
char LANG_IS_EMPTY_STATEMENT[] = "lang.is_empty_statement";
char LANG_IS_ENUM_SPECIFIER[] = "lang.is_enum_specifier";
char LANG_IS_EQUAL_OP[] = "lang.is_equal_op";
char LANG_IS_EXPRESSION_NEST[] = "lang.is_expression_nest";
char LANG_IS_EXPRESSION_STATEMENT[] = "lang.is_expression_statement";
char LANG_IS_FLOATING_LITERAL[] = "lang.is_floating_literal";
char LANG_IS_FOR_STATEMENT[] = "lang.is_for_statement";
char LANG_IS_FUNCTIONAL_DECLARATOR[] = "lang.is_functional_declarator";
char LANG_IS_FUNCTION_CALL[] = "lang.is_function_call";
char LANG_IS_FUNCTION_DEFINITION[] = "lang.is_function_definition";
char LANG_IS_GCC_ATTRIBUTE[] = "lang.is_gcc_attribute";
char LANG_IS_GCC_ATTRIBUTE_VALUE[] = "lang.is_gcc_attribute_value";
char LANG_IS_GLOBAL_QUALIFIED[] = "lang.is_global_qualified";
char LANG_IS_GOTO_STATEMENT[] = "lang.is_goto_statement";
char LANG_IS_GREATER_OR_EQUAL_THAN_OP[] = "lang.is_greater_or_equal_than_op";
char LANG_IS_GREATER_THAN_OP[] = "lang.is_greater_than_op";
char LANG_IS_ID_EXPRESSION[] = "lang.is_id_expression";
char LANG_IS_IF_STATEMENT[] = "lang.is_if_statement";
char LANG_IS_INTEGER_LITERAL[] = "lang.is_integer_literal";
char LANG_IS_LABELED_STATEMENT[] = "lang.is_labeled_statement";
char LANG_IS_LITERAL[] = "lang.is_literal";
char LANG_IS_LOGICAL_AND_OP[] = "lang.is_logical_and_op";
char LANG_IS_LOGICAL_OR_OP[] = "lang.is_logical_or_op";
char LANG_IS_LOWER_OR_EQUAL_THAN_OP[] = "lang.is_lower_or_equal_than_op";
char LANG_IS_LOWER_THAN_OP[] = "lang.is_lower_than_op";
char LANG_IS_MEMBER_ACCESS[] = "lang.is_member_access";
char LANG_IS_MOD_ASSIGNMENT[] = "lang.is_mod_assignment";
char LANG_IS_MODULUS_OP[] = "lang.is_modulus_op";
char LANG_IS_MUL_ASSIGNMENT[] = "lang.is_mul_assignment";
char LANG_IS_MULT_OP[] = "lang.is_mult_op";
char LANG_IS_NAMED_PARAMETER_DECLARATION[] = "lang.is_named_parameter_declaration";
char LANG_IS_NEGATE_OP[] = "lang.is_negate_op";
char LANG_IS_NOT_OP[] = "lang.is_not_op";
char LANG_IS_OR_ASSIGNMENT[] = "lang.is_or_assignment";
char LANG_IS_PARAMETER_DECLARATION[] = "lang.is_parameter_declaration";
char LANG_IS_PLUS_OP[] = "lang.is_plus_op";
char LANG_IS_POINTER_MEMBER_ACCESS[] = "lang.is_pointer_member_access";
char LANG_IS_POSTDECREMENT[] = "lang.is_postdecrement";
char LANG_IS_POSTINCREMENT[] = "lang.is_postincrement";
char LANG_IS_PRAGMA_CUSTOM_CLAUSE_ARGUMENT[] = "lang.is_pragma_custom_clause_argument";
char LANG_IS_PRAGMA_CUSTOM_CLAUSE[] = "lang.is_pragma_custom_clause";
char LANG_IS_PRAGMA_CUSTOM_CONSTRUCT[] = "lang.is_pragma_custom_construct";
char LANG_IS_PRAGMA_CUSTOM_DIRECTIVE[] = "lang.is_pragma_custom_directive";
char LANG_IS_PRAGMA_CUSTOM_LINE[] = "lang.is_pragma_custom_line";
char LANG_IS_PREDECREMENT[] = "lang.is_predecrement";
char LANG_IS_PREINCREMENT[] = "lang.is_preincrement";
char LANG_IS_QUALIFIED_ID[] = "lang.is_qualified_id";
char LANG_IS_REFERENCE_OP[] = "lang.is_reference_op";
char LANG_IS_RETURN_STATEMENT[] = "lang.is_return_statement";
char LANG_IS_SHIFT_LEFT_OP[] = "lang.is_shift_left_op";
char LANG_IS_SHIFT_RIGHT_OP[] = "lang.is_shift_right_op";
char LANG_IS_SHL_ASSIGNMENT[] = "lang.is_shl_assignment";
char LANG_IS_SHR_ASSIGNMENT[] = "lang.is_shr_assignment";
char LANG_IS_STATEMENT[] = "lang.is_statement";
char LANG_IS_STRING_LITERAL[] = "lang.is_string_literal";
char LANG_IS_SUB_ASSIGNMENT[] = "lang.is_sub_assignment";
char LANG_IS_SUBSTRACTION_OP[] = "lang.is_substraction_op";
char LANG_IS_SWITCH_STATEMENT[] = "lang.is_switch_statement";
char LANG_IS_TEMPLATED_DECLARATION[] = "lang.is_templated_declaration";
char LANG_IS_TEMPLATED_FUNCTION_DEFINITION[] = "lang.is_templated_function_definition";
char LANG_IS_TEMPLATE_HEADER[] = "lang.is_template_header";
char LANG_IS_TEMPLATE_ID[] = "lang.is_template_id";
char LANG_IS_TEMPLATE_PARAMETER[] = "lang.is_template_parameter";
char LANG_IS_TRY_BLOCK[] = "lang.is_try_block";
char LANG_IS_UNARY_OPERATION[] = "lang.is_unary_operation";
char LANG_IS_UNQUALIFIED_ID[] = "lang.is_unqualified_id";
char LANG_IS_WHILE_STATEMENT[] = "lang.is_while_statement";
char LANG_IS_XOR_ASSIGNMENT[] = "lang.is_xor_assignment";
char LANG_LHS_ASSIGNMENT[] = "lang.lhs_assignment";
char LANG_LHS_OPERAND[] = "lang.lhs_operand";
char LANG_NESTED_NAME_SPECIFIER[] = "lang.nested_name_specifier";
char LANG_PARAMETER_DECLARATION_NAME[] = "lang.parameter_declaration_name";
char LANG_PRAGMA_CUSTOM_CLAUSE[] = "lang.pragma_custom_clause";
char LANG_PRAGMA_CUSTOM_DECLARATION[] = "lang.pragma_custom_declaration";
char LANG_PRAGMA_CUSTOM_DIRECTIVE[] = "lang.pragma_custom_directive";
char LANG_PRAGMA_CUSTOM[] = "lang.pragma_custom";
char LANG_PRAGMA_CUSTOM_LINE_IS_PARAMETERIZED[] = "lang.pragma_custom_line_is_parameterized";
char LANG_PRAGMA_CUSTOM_LINE[] = "lang.pragma_custom_line";
char LANG_PRAGMA_CUSTOM_LINE_PARAMETER[] = "lang.pragma_custom_line_parameter";
char LANG_PRAGMA_CUSTOM_STATEMENT[] = "lang.pragma_custom_statement";
char LANG_RHS_ASSIGNMENT[] = "lang.rhs_assignment";
char LANG_RHS_OPERAND[] = "lang.rhs_operand";
char LANG_SUBSCRIPTED_EXPRESSION[] = "lang.subscripted_expression";
char LANG_SUBSCRIPT_EXPRESSION[] = "lang.subscript_expression";
char LANG_TEMPLATE_ARGS[] = "lang.template_args";
char LANG_TEMPLATE_HEADER[] = "lang.template_header";
char LANG_TEMPLATE_NAME[] = "lang.template_name";
char LANG_TYPE_SPECIFIER[] = "lang.type_specifier";
char LANG_UNARY_OPERAND[] = "lang.unary_operand";
char LANG_UNQUALIFIED_ID[] = "lang.unqualified_id";
char OMP_CONSTRUCT_BODY[] = "omp.construct_body";
char OMP_CONSTRUCT_DECLARATION[] = "omp.construct_declaration";
char OMP_CONSTRUCT_DIRECTIVE[] = "omp.construct_directive";
char OMP_CUSTOM_CLAUSE_NAME[] = "omp.custom_clause_name";
char OMP_CUSTOM_CONSTRUCT_NAME[] = "omp.custom_construct_name";
char OMP_CUSTOM_DIRECTIVE_NAME[] = "omp.custom_directive_name";
char OMP_DEFAULT_CUSTOM_CLAUSE[] = "omp.default_custom_clause";
char OMP_IS_ATOMIC_CONSTRUCT[] = "omp.is_atomic_construct";
char OMP_IS_BARRIER_DIRECTIVE[] = "omp.is_barrier_directive";
char OMP_IS_COPYIN_CLAUSE[] = "omp.is_copyin_clause";
char OMP_IS_COPYPRIVATE_CLAUSE[] = "omp.is_copyprivate_clause";
char OMP_IS_CRITICAL_CONSTRUCT[] = "omp.is_critical_construct";
char OMP_IS_CUSTOM_CLAUSE[] = "omp.is_custom_clause";
char OMP_IS_CUSTOM_CONSTRUCT_DIRECTIVE[] = "omp.is_custom_construct_directive";
char OMP_IS_CUSTOM_CONSTRUCT[] = "omp.is_custom_construct";
char OMP_IS_CUSTOM_DIRECTIVE[] = "omp.is_custom_directive";
char OMP_IS_DEFAULT_CUSTOM_CLAUSE[] = "omp.is_default_custom_clause";
char OMP_IS_DEFAULT_NONE_CLAUSE[] = "omp.is_default_none_clause";
char OMP_IS_DEFAULT_SHARED_CLAUSE[] = "omp.is_default_shared_clause";
char OMP_IS_FIRSTPRIVATE_CLAUSE[] = "omp.is_firstprivate_clause";
char OMP_IS_FLUSH_DIRECTIVE[] = "omp.is_flush_directive";
char OMP_IS_FOR_CONSTRUCT[] = "omp.is_for_construct";
char OMP_IS_IF_CLAUSE[] = "omp.is_if_clause";
char OMP_IS_LASTPRIVATE_CLAUSE[] = "omp.is_lastprivate_clause";
char OMP_IS_MASTER_CONSTRUCT[] = "omp.is_master_construct";
char OMP_IS_NOWAIT_CLAUSE[] = "omp.is_nowait_clause";
char OMP_IS_NUM_THREADS_CLAUSE[] = "omp.is_num_threads_clause";
char OMP_IS_OMP_CONSTRUCT[] = "omp.is_omp_construct";
char OMP_IS_ORDERED_CLAUSE[] = "omp.is_ordered_clause";
char OMP_IS_ORDERED_CONTRUCT[] = "omp.is_ordered_contruct";
char OMP_IS_PARALLEL_CONSTRUCT[] = "omp.is_parallel_construct";
char OMP_IS_PARALLEL_FOR_CONSTRUCT[] = "omp.is_parallel_for_construct";
char OMP_IS_PARALLEL_SECTIONS_CONSTRUCT[] = "omp.is_parallel_sections_construct";
char OMP_IS_PARALLEL_SINGLE_CONSTRUCT[] = "omp.is_parallel_single_construct";
char OMP_IS_PARAMETER_CLAUSE[] = "omp.is_parameter_clause";
char OMP_IS_PRIVATE_CLAUSE[] = "omp.is_private_clause";
char OMP_IS_REDUCTION_CLAUSE[] = "omp.is_reduction_clause";
char OMP_IS_SCHEDULE_CLAUSE[] = "omp.is_schedule_clause";
char OMP_IS_SECTION_CONSTRUCT[] = "omp.is_section_construct";
char OMP_IS_SECTIONS_CONSTRUCT[] = "omp.is_sections_construct";
char OMP_IS_SHARED_CLAUSE[] = "omp.is_shared_clause";
char OMP_IS_SINGLE_CONSTRUCT[] = "omp.is_single_construct";
char OMP_IS_THREADPRIVATE_DIRECTIVE[] = "omp.is_threadprivate_directive";
char OMP_IS_USER_DEFINED_REDUCTION[] = "omp.is_user_defined_reduction";
char OMP_REDUCTION_FUNCTION[] = "omp.reduction_function";
char OMP_REDUCTION_NEUTER[] = "omp.reduction_neuter";
char OMP_REDUCTION_OPERATOR[] = "omp.reduction_operator";
char OMP_REDUCTION_VARIABLES[] = "omp.reduction_variables";
char OMP_SCHEDULE_CHUNK[] = "omp.schedule_chunk";
char OMP_SCHEDULE_CUSTOM_NAME[] = "omp.schedule_custom_name";
char OMP_SCHEDULE_KIND[] = "omp.schedule_kind";
/* AST attributes */
void register_ast_extended_attributes(void)
{
    extensible_schema_init(&ast_extensible_schema);
    extensible_schema_add_field(&ast_extensible_schema, LANG_ACCESSED_ENTITY, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_ACCESSED_MEMBER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CALLED_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CASTED_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CAST_TYPE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CLASS_SPECIFIER_SYMBOL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_COMPOUND_STATEMENT_LIST, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CONDITIONAL_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CONDITIONAL_FALSE_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_CONDITIONAL_TRUE_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_DECLARATION_DECLARATORS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_DECLARATION_SPECIFIERS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_DECLARED_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_DECLARED_PARAMETER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_ENUM_SPECIFIER_SYMBOL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_EXPRESSION_DECREMENTED, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_EXPRESSION_INCREMENTED, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_EXPRESSION_NESTED, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FOR_BODY_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FOR_CONDITION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FOR_INIT_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FOR_ITERATION_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FUNCTION_ARGUMENTS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FUNCTION_BODY, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FUNCTION_DECLARATOR, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FUNCTION_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_FUNCTION_SYMBOL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_GCC_ATTRIBUTE_LIST, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_GCC_ATTRIBUTE_VALUE_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_GCC_ATTRIBUTE_VALUE_ARGS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_INITIALIZER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ACCESSED_MEMBER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ADD_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ADDITION_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_AND_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ARRAY_SUBSCRIPT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BINARY_OPERATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BITWISE_AND_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BITWISE_OR_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BITWISE_XOR_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BOOLEAN_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_BREAK_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CASE_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CAST, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CHARACTER_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CLASS_SPECIFIER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_COMMA_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_COMPLEMENT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_COMPOUND_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CONDITIONAL_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_CONTINUE_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DECLARATION_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DECLARED_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DEFAULT_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DERREFERENCE_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DIFFERENT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DIV_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DIVISION_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_DO_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_EMPTY_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ENUM_SPECIFIER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_EQUAL_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_EXPRESSION_NEST, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_EXPRESSION_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_FLOATING_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_FOR_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_FUNCTIONAL_DECLARATOR, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_FUNCTION_CALL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_FUNCTION_DEFINITION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GCC_ATTRIBUTE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GCC_ATTRIBUTE_VALUE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GLOBAL_QUALIFIED, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GOTO_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GREATER_OR_EQUAL_THAN_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_GREATER_THAN_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_ID_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_IF_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_INTEGER_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LABELED_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LOGICAL_AND_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LOGICAL_OR_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LOWER_OR_EQUAL_THAN_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_LOWER_THAN_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_MEMBER_ACCESS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_MOD_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_MODULUS_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_MUL_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_MULT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_NAMED_PARAMETER_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_NEGATE_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_NOT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_OR_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PARAMETER_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PLUS_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_POINTER_MEMBER_ACCESS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_POSTDECREMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_POSTINCREMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PRAGMA_CUSTOM_CLAUSE_ARGUMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PRAGMA_CUSTOM_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PRAGMA_CUSTOM_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PRAGMA_CUSTOM_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PRAGMA_CUSTOM_LINE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PREDECREMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_PREINCREMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_QUALIFIED_ID, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_REFERENCE_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_RETURN_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SHIFT_LEFT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SHIFT_RIGHT_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SHL_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SHR_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_STRING_LITERAL, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SUB_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SUBSTRACTION_OP, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_SWITCH_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TEMPLATED_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TEMPLATED_FUNCTION_DEFINITION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TEMPLATE_HEADER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TEMPLATE_ID, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TEMPLATE_PARAMETER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_TRY_BLOCK, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_UNARY_OPERATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_UNQUALIFIED_ID, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_WHILE_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_IS_XOR_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_LHS_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_LHS_OPERAND, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_NESTED_NAME_SPECIFIER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PARAMETER_DECLARATION_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_LINE_IS_PARAMETERIZED, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_LINE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_LINE_PARAMETER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_PRAGMA_CUSTOM_STATEMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_RHS_ASSIGNMENT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_RHS_OPERAND, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_SUBSCRIPTED_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_SUBSCRIPT_EXPRESSION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_TEMPLATE_ARGS, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_TEMPLATE_HEADER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_TEMPLATE_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_TYPE_SPECIFIER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_UNARY_OPERAND, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, LANG_UNQUALIFIED_ID, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CONSTRUCT_BODY, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CONSTRUCT_DECLARATION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CONSTRUCT_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CUSTOM_CLAUSE_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CUSTOM_CONSTRUCT_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_CUSTOM_DIRECTIVE_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_DEFAULT_CUSTOM_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_ATOMIC_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_BARRIER_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_COPYIN_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_COPYPRIVATE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_CRITICAL_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_CUSTOM_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_CUSTOM_CONSTRUCT_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_CUSTOM_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_CUSTOM_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_DEFAULT_CUSTOM_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_DEFAULT_NONE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_DEFAULT_SHARED_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_FIRSTPRIVATE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_FLUSH_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_FOR_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_IF_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_LASTPRIVATE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_MASTER_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_NOWAIT_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_NUM_THREADS_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_OMP_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_ORDERED_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_ORDERED_CONTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PARALLEL_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PARALLEL_FOR_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PARALLEL_SECTIONS_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PARALLEL_SINGLE_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PARAMETER_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_PRIVATE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_REDUCTION_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_SCHEDULE_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_SECTION_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_SECTIONS_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_SHARED_CLAUSE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_SINGLE_CONSTRUCT, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_THREADPRIVATE_DIRECTIVE, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_IS_USER_DEFINED_REDUCTION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_REDUCTION_FUNCTION, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_REDUCTION_NEUTER, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_REDUCTION_OPERATOR, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_REDUCTION_VARIABLES, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_SCHEDULE_CHUNK, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_SCHEDULE_CUSTOM_NAME, sizeof(tl_type_t));
    extensible_schema_add_field(&ast_extensible_schema, OMP_SCHEDULE_KIND, sizeof(tl_type_t));
}
